on:
  push:
    branches:
      - master
      - main
  create:
    tags:

name: PUBLISH
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install
        run:  npm install
      - name: make
        run:  dcl run build
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}